### PR TITLE
Update gcs_load_all() use of file.copy()

### PR DESCRIPTION
**Pull request by jasonmhoule**
For #112

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Nice, this looks a lot simpler and I was having problems with this in another package too. So this covers all file situations?

**Comment by jasonmhoule** [comment]
I think it should, do you have specific file situations in mind? Key is that it copies at the main directory level rather than file by file, depends on the integrity of file.copy() to do the heavy lifting.

**Comment by MarkEdmondson1234** [comment]
I'll run it through my local tests before merge, but looks great, much better.

**Comment by MarkEdmondson1234** [comment]
Thanks a lot :>)

**Pull request merged**
