### PR TITLE
added size_bytes

### LINKED ISSUE #156: Get Full size of object, in bytes
I would like the `size` (in bytes) to check against a listing to make sure all bytes are downloaded.  The issue is that googleCloudStorageR automatically formats this: 
https://github.com/cloudyr/googleCloudStorageR/blob/ae8670ed60f7bd70f1b9399565a473f90a3134ff/R/objects.R#L94
And you can't set an option for `format_object_size`.  I think if you use something like:

```r
format_object_size(getOption("googleCloudStorageR.format_units", default = "auto"))
```
Then you can set an `option("googleCloudStorageR.format_units" = "b")` then this should work I think

``` r
head(googleCloudStorageR::gcs_list_objects()$size)
#> [1] "218.8 Mb"  "137.9 Mb"  "1.1 Kb"    "45.6 Kb"   "74 bytes"  "159 bytes"
head(googleCloudStorageR::gcs_list_objects(detail = "full")$size)
#> [1] "218.8 Mb"  "137.9 Mb"  "1.1 Kb"    "45.6 Kb"   "74 bytes"  "159 bytes"
```

<sup>Created on 2022-03-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by muschellij2**
Added size_bytes to fix #156 instead of #157

### CODE REVIEW

**Comment by muschellij2** [comment]
Got a warning with `rlang`.  I think GH actions still can check this, but likely need auth in there.

**Comment by muschellij2** [comment]
Thsi should be good to go I think.

**Comment by muschellij2** [comment]
The `fields` parameter allows you to subset the data so that the request is a lower payload, similar to https://github.com/googleapis/python-storage/blob/9b2931430b0796ffb23ec4efacd82dacad36f40f/google/cloud/storage/blob.py#L692

so you can enable functions like this
```r
gcs_object_exists = function(object_name,
                             bucket = gcs_get_global_bucket()){
  out = try({
    gcs_get_object(object_name = object_name, 
                   bucket = bucket,
                   meta = TRUE,
                   fields = "name")
  }, silent = TRUE)
  !inherits(out, "try-error")
}
```

The reason I didn't add this function is that there may be errors that are due to auth, so you could do something with the status_code like:

```r
gcs_object_exists = function(object_name,
                             bucket = gcs_get_global_bucket()){
  out = try({
    gcs_get_object(object_name = object_name, 
                   bucket = bucket,
                   meta = TRUE,
                   fields = "name")
  }, silent = TRUE)
  !inherits(out, "try-error") && !inherits(attr(out, "condition"), "http_404")
}
```

**Comment by MarkEdmondson1234** [comment]
Yes agreed, using `fields` for very big metadata would help download size.

The new error conditions on 404 etc are intended to be used something like this:

```r
gcs_object_exists = function(object_name,
                             bucket = gcs_get_global_bucket()){
  tryCatch({
    gcs_get_object(object_name = object_name, 
                   bucket = bucket,
                   meta = TRUE,
                   fields = "name")
  },
  http_404 = {FALSE})
}
```

**Comment by MarkEdmondson1234** [comment]
Thanks!  Sorry it took so long, but the book is nearly done now ;)

**Pull request merged**
